# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in latest_stock_price.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rest-client", "~> 2.1"

gem "rubocop", "~> 1.21"
